---
title: "IMPC summary stat exploratory data analysis"
author: "Donghyung Lee"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{IMPC summary stat exploratory data analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Here, I will conduct an exploratory data analysis on the IMPC summary statistics.
```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE)
```


## Load R packages
```{r load_packages, message=FALSE}
rm(list=ls())
#library(plyr)
#library(ggplot2)
library(RColorBrewer)
#library(reshape2)
#library(mvtnorm)
#library(corrplot)
library(data.table) #fread
library(knitr)
library(kableExtra)
library(plotly)
library(pheatmap)
library(heatmaply)

color.vec <- brewer.pal(8, "Set1")
```

## Reading the summary data
```{r load_data}
## load IMPC summary stats 7.0
IMPC.summary.stats.file <- "~/Dropbox/KOMP/results/IMPC_Summary_Stat_Study/R_input/version_7.0/IMPC_ALL_statistical_results.csv"
IMPC.summary.stats <- as.data.frame(fread(IMPC.summary.stats.file, header=TRUE, sep=","))
IMPC.summary.stats$marker_symbol_combined <- paste0(IMPC.summary.stats$marker_symbol,"_",IMPC.summary.stats$zygosity)
IMPC.summary.stats$intermediate_mp_term_name <- NULL
IMPC.summary.stats$intermediate_mp_term_id <- NULL
dim(IMPC.summary.stats)
colnames(IMPC.summary.stats)
```

## First part of summary table
```{r head_data}
kable(as.data.frame(head(IMPC.summary.stats))) %>%
  kable_styling(bootstrap_options = c("striped","condensed","responsive"), full_width = F, position="left") %>%
  scroll_box(width = "120%")
```

## Phenotyping Centers
```{r phenotyping_centers}
pheno.center <- as.data.frame.vector(table(IMPC.summary.stats$phenotyping_center))
colnames(pheno.center) <- "Counts"
kable(pheno.center) %>% 
  kable_styling(bootstrap_options = c("striped","condensed","responsive"), full_width = F)
```

## Phenotype Procedures & Centers
```{r pheno_assay_center}
assay.center <- as.data.frame.matrix(table(IMPC.summary.stats$procedure_name, IMPC.summary.stats$phenotyping_center))
kable(assay.center) %>% 
  kable_styling(bootstrap_options = c("striped","condensed","responsive"), full_width = F) %>%
  scroll_box(height = "500px")
```

## Phenotype Names & Centers
```{r phenotype_names}
pheno.names.centers <- as.data.frame.matrix(table(IMPC.summary.stats$parameter_name, IMPC.summary.stats$phenotyping_center))
kable(pheno.names.centers) %>% 
  kable_styling(bootstrap_options = c("striped","condensed","responsive"), full_width = F) %>%
  scroll_box(height = "500px")

pheno.names <- as.data.frame.vector(table(IMPC.summary.stats$parameter_name))
colnames(pheno.names) <- "Counts"
ggplot(data=pheno.names, aes(pheno.names$Counts)) + geom_histogram() + labs(x="Phenotype", y="Count")
```

## Mutant Lines & Centers
```{r mutant_lines}
mutant.lines.centers <- as.data.frame.matrix(table(IMPC.summary.stats$marker_symbol_combined, IMPC.summary.stats$phenotyping_center))
kable(mutant.lines.centers) %>% 
  kable_styling(bootstrap_options = c("striped","condensed","responsive"), full_width = F) %>%
  scroll_box(height = "500px")

mutant.lines <- as.data.frame.vector(table(IMPC.summary.stats$marker_symbol_combined))
colnames(mutant.lines) <- "Counts"
ggplot(data=mutant.lines, aes(mutant.lines$Counts)) + geom_histogram() + labs(x="Mutant Line", y="Count")
```

## Phenotypes & Mutant Lines
```{r pheno_mutant}
pheno.mutant <- as.data.frame.matrix(table(IMPC.summary.stats$marker_symbol_combined, IMPC.summary.stats$parameter_name))
dim(pheno.mutant)
class(pheno.mutant)

m <- list(
  l = 150,
  r = 50,
  b = 200,
  t = 10,
  pad = 4
)

plot_ly(x=colnames(pheno.mutant), y=rownames(pheno.mutant), z=as.matrix(pheno.mutant), colors= brewer.pal(9, "Reds"), type="heatmap") %>% layout(autosize=F, width=800, height=800, margin=m)
table(as.matrix(pheno.mutant))
```
